src/Speech/Controllers/GoalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Speech.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Speech.Controllers
{
    public class GoalController : Controller
    {

        public SpeechDbContext _db;

        public GoalController(SpeechDbContext db)
        {
            _db = db;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            ViewBag.ProfileId = new SelectList(_db.Profiles, "ProfileId", "ClientFirst");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Goal goal)
        {
            goal.Completed = false;
            _db.Goals.Add(goal);
            _db.SaveChanges();
            return RedirectToAction("Clients", "Admin");
        }

        public IActionResult Complete(int id)
        {
            var thisGoal = _db.Goals.FirstOrDefault(goals => goals.GoalId == id);
            thisGoal.Completed = true;
            _db.Entry(thisGoal).State = EntityState.Modified;
            _db.SaveChanges();
            return View(thisGoal);
        }


        public IActionResult Edit(int id)
        {
            var thisGoal = _db.Goals.FirstOrDefault(goals => goals.GoalId == id);
            return View(thisGoal);
        }

        [HttpPost]
        public IActionResult Edit(Goal goal)
        {
            _db.Entry(goal).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Clients","Admin");
        }

        public IActionResult Delete(int id)
        {
            var thisGoal = _db.Goals.FirstOrDefault(goals => goals.GoalId == id);
            return View(thisGoal);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisGoal = _db.Goals.FirstOrDefault(goals => goals.GoalId == id);
            _db.Goals.Remove(thisGoal);
            _db.SaveChanges();
            return RedirectToAction("Clients", "Admin");
        }
    }
}

src/Speech/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Speech.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Speech.Controllers
{
    public class NoteController : Controller
    {
        public SpeechDbContext _db;

        public NoteController(SpeechDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Create(int id)
        {
            ViewBag.ProfileId = new SelectList(_db.Profiles, "ProfileId", "ClientFirst");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Note note, Profile profile)
        {
            note.Date = DateTime.Now.ToLocalTime();
            _db.Notes.Add(note);
            _db.SaveChanges();

            //profile.ClientFirst = _db.Profiles.ClientFirst.Where(p => p.ProfileId == note.ProfileId);

            Console.WriteLine("!!!!!!!!!!!!" + profile);
            return RedirectToAction("Clients", "Admin");
        }

        public IActionResult Edit(int id)
        {
            var thisNote = _db.Notes.FirstOrDefault(notes => notes.NoteId == id);
            return View(thisNote);
        }

        [HttpPost]
        public IActionResult Edit(Note note)
        {
            note.Date = DateTime.Now.ToLocalTime();
            _db.Entry(note).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Clients", "Admin");
        }

        public IActionResult Delete(int id)
        {
            var thisNote = _db.Notes.FirstOrDefault(notes => notes.NoteId == id);
            return View(thisNote);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var thisNote = _db.Notes.FirstOrDefault(notes => notes.NoteId == id);
            _db.Notes.Remove(thisNote);
            _db.SaveChanges();
            return RedirectToAction("Clients", "Admin");
        }
    }
}

src/Speech/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Speech.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Speech.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        public SpeechDbContext _db;
        public UserManager<ApplicationUser> _userManager;
        public RoleManager<IdentityRole> _roleManager;

        public RolesController(SpeechDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var roles = _db.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IdentityRole role)
        {
            role.NormalizedName = role.Name.ToString().ToUpper();
            _db.Roles.Add(role);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Edit(string roleId)
        {
            var thisRole = _db.Roles.Where(r => r.Id.Equals(roleId, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return View(thisRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IdentityRole role)
        {
            try
            {
                var thisRole = _db.Roles.Where(r => r.Id.Equals(role.Id, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
                _db.Roles.Attach(thisRole);
                thisRole.Name = role.Name;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return View(role);
            }
        }

        public IActionResult Delete(string RoleName)
        {
            var thisRole = _db.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            return View(thisRole);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteRole(string RoleName)
        {
            var thisRole = _db.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            _db.Roles.Remove(thisRole);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Assign()
        {
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(string UserName, string RoleName)
        {
            var user = await _userManager.FindByNameAsync(UserName);
            await _userManager.AddToRoleAsync(user, RoleName);
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetRoles(string UserName)
        {
            if (!string.IsNullOrWhiteSpace(UserName))
            {
                ViewBag.RolesForThisUser = await _userManager.GetRolesAsync(await _userManager.FindByNameAsync(UserName));
            }
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return View("Assign");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(string UserName, string RoleName)
        {
            var user = await _userManager.FindByNameAsync(UserName);

            if (await _userManager.IsInRoleAsync(user, RoleName))
            {
                await _userManager.RemoveFromRoleAsync(user, RoleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            ViewBag.RoleName = new SelectList(_db.Roles, "Name", "Name");
            ViewBag.UserName = new SelectList(_db.Users, "UserName", "UserName");
            return View("Assign");
        }
    }
}

src/Speech/Views/Admin/Clients.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Speech.Models.Profile>

<div class="container user-form">

    <h1>All Clients</h1>
    <hr />

    <ol>
        @foreach (var client in Model)
        {
            <li class="assign-role">@Html.ActionLink((string)client.ClientFirst + " " + client.ClientLast, "Details", new { id = client.ProfileId })</li>
        }
    </ol>

    <button class="btn">@Html.ActionLink("Assign goals to a client", "Create", "Goal")</button>
    <button class="btn">@Html.ActionLink("Write a note for a client", "Create", "Note")</button>


</div>

src/Speech/Views/Admin/CreateNote.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@model Speech.Models.Note


<div class="container user-form">
    <h1>Write a note for a client</h1>
    <hr />

    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-sm-3">
                <label>Client: </label>
            </div>
            <div class="col-sm-9">
                @Html.DropDownList("ProfileId")
            </div>
        </div>

        @Html.LabelFor(model => model.Description)
        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })

        <button type="submit" class="btn">Add note</button>
    }

    <h4>@Html.ActionLink("Back to Client Index", "Clients", "Admin")</h4>
</div>

src/Speech/Views/Admin/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Speech.Models.Profile

<div class="container">
    <h1>@Html.DisplayFor(model => model.ClientFirst) @Html.DisplayFor(model => model.ClientLast)</h1>
    <hr />
    <div class="row">
        <div class="col-sm-3">
            <h4><span class="property">Name:</span></h4>
        </div>
        <div class="col-sm-9">
            <h4> @Html.DisplayFor(model => model.ClientFirst) @Html.DisplayFor(model => model.ClientLast)</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <h4><span class="property">Birthdate:</span></h4>
        </div>
        <div class="col-sm-9">
            <h4> @Html.DisplayFor(model => model.DOB)</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <h4><span class="property">Parent name:</span></h4>
        </div>
        <div class="col-sm-9">
            <h4> @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <h4><span class="property">Parent comment:</span></h4>
        </div>
        <div class="col-sm-9">
            <h4> @Html.DisplayFor(model => model.Comment)</h4>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-sm-3">
            <h4><span class="property">Goals:</span></h4>
        </div>
        <div class="col-sm-9">

            @if (Model.Goals.Count > 0)
            {

                <div class="row">
                    <div class="col-sm-9">
                        <h4><span class="property">Description:</span></h4>
                    </div>
                    <div class="col-sm-3">
                        <h4><span class="property">Status:</span></h4>
                    </div>
                </div>

                @foreach (var goal in Model.Goals)
                {

                    <div class="row">
                        <div class="col-sm-9">
                            <h4>@goal.Description</h4>
                            <p>@Html.ActionLink("Edit", "Edit", "Goal", new { id = goal.GoalId, profileId = goal.ProfileId }) | @Html.ActionLink("Delete", "Delete", "Goal", new { id = goal.GoalId, profileId = goal.ProfileId})</p>
                        </div>
                        <div class="col-sm-3">
                            @if (goal.Completed == false)
                            {
                                <div id="completed-goal-@goal.GoalId">

                                    <h4>
                                        <span class="not-met">Not met.</span>
                                        <br />
                                        <button class="complete" id="@goal.GoalId">Mark this goal as met</button>
                                    </h4>
                                </div>
                            }
                            else
                            {
                                <h4 class="met">Met.</h4>

                            }
                        </div>
                    </div>
                }
            }
            else
            {
                <h4>No goals have been added yet</h4>
            }
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-sm-3">
            <h4><span class="property">Notes:</span></h4>
        </div>
        <div class="col-sm-9">

            @if (Model.Notes.Count > 0)
            {

                <div class="row">
                    <div class="col-sm-9">
                        <h4><span class="property">Description:</span></h4>
                    </div>
                    <div class="col-sm-3">
                        <h4><span class="property">Date Added:</span></h4>
                    </div>
                </div>

                @foreach (var note in Model.Notes)
                {

                    <div class="row">
                        <div class="col-sm-9">
                            <h4>@note.Description</h4>
                            <p>@Html.ActionLink("Edit", "Edit", "Note", new { id = note.NoteId, profileId = note.ProfileId }) | @Html.ActionLink("Delete", "Delete", "Note", new { id = note.NoteId, profileId = note.ProfileId })</p>

                        </div>
                        <div class="col-sm-3">
                            <h5>@note.Date</h5>
                        </div>
                    </div>
                }
            }
            else
            {
                <h4>No notes have been added yet</h4>
            }
        </div>
    </div>

    <br />
    <button class="btn" id="role-button">@Html.ActionLink("Create a goal", "Create", "Goal")</button>
    <button class="btn" id="role-button">@Html.ActionLink("Add a note", "Create", "Note")</button>
    <h4>@Html.ActionLink("Back to client list", "Clients", "Admin")</h4>

</div>

src/Speech/Views/Admin/EditGoal.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Speech.Models.Goal


<div class="container user-form">


    <h2>Edit Goal</h2>
    <hr />
    <h4>Edit this goal: @Html.DisplayFor(model => model.Description)</h4>

    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.GoalId)
        @Html.HiddenFor(model => model.ProfileId);

        @Html.LabelFor(model => model.Description)
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })

        <input type="submit" value="Save" class="btn" />
    }
    <h4>@Html.ActionLink("Back to client list", "Client")</h4>
</div>

src/Speech/Views/Admin/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Speech.Models.ApplicationUser>

<div class="container user-form">

    <h1>All users</h1>
    <hr />

    <ol>
        @foreach (var user in Model)
        {
            <li class="assign-role">@user.UserName</li>
        }

    </ol>
    <button class="btn" type="button">@Html.ActionLink("Roles Listing", "Index", "Roles")</button>
   

</div>