src/Speech/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Speech.Models;
using Microsoft.EntityFrameworkCore;

namespace Speech.Controllers
{
    public class ProfileController : Controller
    {
        private SpeechDbContext db = new SpeechDbContext();
        public IActionResult Index(string userName)
        {
            var thisUser = db.Profiles.FirstOrDefault(profiles => profiles.UserName == userName);
            return View(thisUser);
        }

        public IActionResult Edit(string userName)
        {
            var thisProfile = db.Profiles.FirstOrDefault(profiles => profiles.UserName == userName);
            return View(thisProfile);
        }

        [HttpPost]
        public IActionResult Edit(Profile profile, string userName)
        {
            db.Entry(profile).State = EntityState.Modified;
            var thisUser = db.Profiles.FirstOrDefault(profiles => profiles.UserName == userName);

            db.SaveChanges();
            return RedirectToAction("Index", new { userName = thisUser.UserName });
        }

        public IActionResult Progress(string userName)
        {
            var thisUser = db.Profiles.Include(profiles => profiles.Goals).Include(profiles => profiles.Notes).FirstOrDefault(profiles => profiles.UserName == userName);
            return View(thisUser);
        }
    }
}

src/Speech/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Speech.Controllers
{
    public class ResourcesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Milestones()
        {
            return View();
        }

        public IActionResult Resources()
        {
            return View();
        }
    }
}

src/Speech/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Speech.Models;
using Microsoft.EntityFrameworkCore;

namespace Speech.Controllers
{
    public class ReviewController : Controller
    {
        private SpeechDbContext db = new SpeechDbContext();
        public IActionResult Index()
        {
            return View(db.Reviews.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Review review)
        {
            db.Reviews.Add(review);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/Speech/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Speech Solutions</title>
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="js/bootstrap-carousel.js"></script>
    <script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js" type="text/javascript"></script>
    <link rel="stylesheet" href="css/bootstrap.css" type="text/css">
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
</head>
<body>
    <div id="container">
        <nav class="navbar navbar-inverse navbar-fixed-top top-navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">SPEECH SOLUTIONS</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("About Us", "Index", "About")</li>
                                <li>@Html.ActionLink("Reviews", "Index", "Review")</li>
                                <li>@Html.ActionLink("Contact Us", "Contact", "About")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Resources<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Speech Milestones", "Milestones", "Resources")</li>
                                <li>@Html.ActionLink("Helpful Resources", "Resources", "Resources")</li>
                            </ul>
                        </li>
                        @*<li class="nav-link">
                            @Html.ActionLink("Schedule Consultation", "Schedule", "Home")
                        </li>*@
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sessions<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Schedule Consultation", "Schedule", "Home")</li>
                                <li>@Html.ActionLink("Video Session", "Video", "Home")</li>
                            </ul>
                        </li>
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated && !User.IsInRole("Admin"))
                         {
                            <li class="nav-link">
                                @Html.ActionLink("Progress", "Progress", "Profile", new { userName = User.Identity.Name })
                            </li>
                            <li class="nav-link">
                                @Html.ActionLink("Account Info", "Index", "Profile", new { userName = User.Identity.Name })
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Users/Roles", "Index", "Admin")</li>
                                    <li>@Html.ActionLink("Clients", "Clients", "Admin")</li>
                                </ul>
                            </li>
                            
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-link">
                                @Html.ActionLink("Log out", "LogOff", "Account")
                            </li>
                        }
                        else
                        {
                            <li class="nav-link">@Html.ActionLink("Register", "Register", "Account")</li>
                            <li class="nav-link">@Html.ActionLink("Login", "Login", "Account")</li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

        <div class="body-div">
            <span class="skype-button rounded " data-contact-id="nicky9022"></span>
            <script src="https://latest-swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
            
            @RenderBody()


            <div id="footer">
                <div class="row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-3">
                        <p class="footer-heading">Contact Us</p>
                        <hr />
                        <p><img class="icon" src="~/images/contact.png" />@Html.ActionLink("Contact Us Page", "Contact", "About")</p>
                        <p><img class="icon" src="~/images/phone.png" />1-800-666-5555</p>
                        <p><img class="icon" src="~/images/email.png" />SpeechSolutions2@gmail.com</p>
                    </div>
                    <div class="col-sm-3">
                        <p class="footer-heading">Useful Links</p>
                        <hr />
                        <p>@Html.ActionLink("About Us", "Company", "About")</p>
                        <p>@Html.ActionLink("Schedule an appointment", "Schedule", "Home")</p>
                        <p>@Html.ActionLink("Helpful Resources", "Resources", "Resources")</p>
                    </div>
                    <div class="col-sm-2">
                        <p class="footer-heading">Connect With Us</p>
                        <hr />
                        <p><a href="http://www.facebook.com" target="_blank"><img class="icon" src="~/images/facebook2.png">Facebook</a></p>
                        <p><a href="http://www.linkedin.com" target="_blank"><img class="icon" src="~/images/linkedin2.png">Linked In</a></p>
                        <p><a href="http://www.twitter.com" target="_blank"><img class="icon" src="~/images/twitter2.png" />Twitter</a></p>
                    </div>
                    <div class="col-sm-2" </div>
                </div>
            </div>
        </div>
    </div>
 
</body>
</html>